### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by MarkStega** [BBGONE/JRIApp#1]
With a straight clone of the repository many of the references in RIAppDemo.sln projects are not resolved. I believe it may have to do with the hint paths in the csproj files. An example is in RIApp.DataService.EF6_CF where the references to entityframework and entityframework.sqlserver do not resolve. The snippets from the project are:

`    <Reference Include="EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL">
      <HintPath>..\..\..\DEMOS\RIAppDemo\packages\EntityFramework.6.1.3\lib\net45\EntityFramework.dll</HintPath>
      <Private>True</Private>    </Reference>`

`    <Reference Include="EntityFramework.SqlServer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL">
      <HintPath>..\..\..\DEMOS\RIAppDemo\packages\EntityFramework.6.1.3\lib\net45\EntityFramework.SqlServer.dll</HintPath>
      <Private>True</Private>
    </Reference>
`

It looks like the issue may be that the directory RIAppDemo in the snippet is now RIAppDemoMVC in the repository.

**Comment by BBGONE** [comment]
Fixed. 
I moved projects - RIAPP.DataService.WebApi, RIAPP.DataService.Mvc, RIAPP.DataService.EF6_CF
from another solution where packages folder was in another place.
They started to reference missed assemblies from the bin folders.
It worked at my computer because i had bin folders intact, but i removed them when i uploaded the projects to GITHUB and the references had broken completely.
Now i restored Nuget packages and references and tested that the Git clone is built.
